rvm:
  - 1.8.7
  - 1.9.2
  - 1.9.3
  - rbx
  - rbx-2.0
  - jruby
  - ruby-head
env:
  - "rack=1.3.4"
  - "rack=master"
  - "tilt=1.3.3"
  - "tilt=master"
notifications:
  recipients:
    - k.haase@finn.de
