---
language: ruby

rvm:
  - 2.2
  - rbx-2
  - jruby
  - jruby-head
  - ruby-head

sudo: false

matrix:
  include:
    - { rvm: 2.2, env: rack=master }
    - { rvm: 2.2, env: tilt=master }
  allow_failures:
    - env: rack=master
    - env: tilt=master
    - rvm: rbx-2
    - rvm: ruby-head
    - rvm: jruby-head
