rvm:
  - 1.8.7
  - 1.9.2
  - rbx
  - rbx-2.0
  - ree
  - jruby
  - ruby-head
env:
  - "rack=1.3.0"
  - "rack=master"
  - "tilt=1.3.2"
  - "tilt=master"
notifications:
  recipients:
    - k.haase@finn.de
