---
language: ruby

rvm:
  - 2.2
  - jruby-9.0.0.0
  - ruby-head
  - jruby-head
  - rbx-2

sudo: false

matrix:
  include:
    - { rvm: 2.2, env: rack=master }
    - { rvm: 2.2, env: tilt=master }
  allow_failures:
    - env: rack=master
    - env: tilt=master
    - rvm: ruby-head
    - rvm: jruby-head
    - rvm: rbx-2
