---
language: ruby

rvm:
  - 2.2.2
  - 2.2.3
  - ruby-head
  - rbx-2
  - jruby-9.0.0.0
  - jruby-head

sudo: false

matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-head
    - rvm: rbx-2
